export cost URL = 'http://localhost:5000'

export const GET_COMPONENTS = 'GET_COMPONENTS'
export const GET_COMPONENTS_ERROR = 'GET_COMPONENTS_ERROR'

export const UPDATE_COMPONENTS = 'UPDATE_COMPONENTS'
export const UPDATE_COMPONENTS_ERROR = 'UPDATE_COMPONENTS_ERROR'

export const GET_GOOGLE = 'GET_GOOGLE'
export const GET_GOOGLE_ERROR = 'GET_GOOGLE_ERROR'

export const GET_TWITTER = 'GET_TWITTER'
export const GET_TWITTER_ERROR = 'GET_TWITTER_ERROR'

export const GET_WEATHER = 'GET_WEATHER'
export const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'

export const GET_NEWS = 'GET_NEWS'
export const GET_NEWS_ERROR = 'GET_NEWS_ERROR'

export const GET_GREETING = 'GET_GREETING'
